### ISSUE TITLE
Modification of point cloud fusion method

### ISSUE THREAD

**Issue by YuhsiHu** [TQTQliu/ET-MVSNet#7]
First of all, I want to thank you for your great work and express my gratitude for your open-source code.

The paper mentioned that the baseline is MVSTER. After adding the epipolar transformer, the score on the DTU data set has been greatly improved. However, I found that the **dypcd script** used in your code is **different** from that of MVSTER. We know that even for the same depth map, using different fusion methods or fusion parameters, the results will be very different. In your ablation experiments, are you using the exact same fusion script as MVSTER? Would such an experiment be fair if different fusion scripts were used?

I tried deleting the ET module, and as long as I used the "updated" fusion script, I could still achieve similar scores. Here are some of my results. (**ET** means using fusion scripts from your code repository, and **regular** means using scripts from MVSTER and other similar methods.)

|experiment|fusion method|accuracy|completeness|overall|
|-|-|-|-|-|
|MVSTER (original paper)|regular|0.350|0.276|0.313|
|MVSTER (ET paper)|regular|0.351|0.284|0.318|
|ET-MVSNet (ET paper)|ET|0.329|0.253|0.291|
|ET-MVSNet (my PC)|ET|0.3291|0.2567|0.2929|
|ET-MVSNet but delete ET|ET|0.3272|0.2590|0.2931|
|ET-MVSNet but delete ET|regular|0.3514|0.2832|0.3173|

The changes to the fusion script played a big role in the model's performance on the DTU dataset.

I'm looking forward to your explanation about it, thank you!

**Comment by TQTQliu** [comment]
Thank you for your interest in our work. First of all, fusion methods are not unified in the MVS field, and different MVS methods adopt different fusion methods. Regarding our revised fusion method, we have mentioned it in the supplementary material and released the code. Secondly, the baseline we use is not the original mvster, for example, we did not use its monocular depth estimation branch, and in our experiments, the ET module can improve the performance of depth and point cloud metrics on both dtu and TT datasets.

**Comment by YuhsiHu** [comment]
Thank you for your reply! 

Yes, I understand that compared to MVSTER, your code has deleted the MDE module, which is why your baseline is worse than the original article. It is totally reasonable. 

I know that different methods use different fusion strategies, such as gipupa, dypcd, etc. Have you applied this better fusion strategy to MVSTER in the ablation experiment?

**Comment by TQTQliu** [comment]
Apologies for the late reply, as we have been occupied with other projects recently. Our experiments were conducted following the mvster approach. Different MVS methods employ various fusion techniques, as you mentioned, such as pcd, dypcd, gipuma,open3d,etc. In addition, there are also some customized fusion methods. Effectively fusing deep maps into point clouds is a significant challenge and key issue within the MVS field. It's hard to definitively assert which fusion method is universally best since performance can vary depending on the dataset and the specific methodology used. The fusion method we adopted is based on the phenomena observed in the depth output and point cloud generated by our method. If you are a researcher in the MVS field, you could consider trying out the fusion method we employed. Best wishes！

**Comment by YuhsiHu** [comment]
Thank you for your response, however, it does not address my concerns.

In the baseline results, it seems that you utilized a default fusion method, but for your proposed ET module, there appears to have been a switch to your updated fusion method. This change seems to have led to performance improvements being attributed to the ET module, which may not entirely reflect its true impact. The MVSTER method achieves comparable scores using the updated fusion method alone on DTU, without the need for the ET module. Therefore, attributing the performance gains solely to the Epipolar Transformer in the ablation study seems unjustified.
